### ISSUE TITLE
Invalid token signature

### ISSUE THREAD

**Issue by fidcn** [tkhamez/eve-srp#21]
Setup SRP using manual install method using 1.2.0  from releases.

When logging in, upon redirect from SSO character selection back to SRP app, error is thrown "Invalid token signature."

Using Neucore provider, switch to Esi interface provider and still had same result. Secure cookie in .env set to 0 or 1 make no difference as well.

**Comment by tkhamez** [comment]
That sounds like the PHP extension `gmp` is not installed on your server - I should add that to the instructions.

**Comment by fidcn** [comment]
That was it! thank you!
